services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  postgres-staging:
    image: postgres:latest
    container_name: postgres-staging
    env_file:
      - .env.staging
    ports:
      - '5433:5432'
    volumes:
      - pgdata-staging:/var/lib/postgresql/data

volumes:
  pgdata-dev:
  pgdata-staging:
