name: Run Staging Tests

on:
  push:
    branches:
      - fix/296-environment-variables-not-detected-in-ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Load Node version from .env
        id: node-version
        run: |
          echo "NODE_VERSION=$(grep NODE_VERSION .env.staging | cut -d '=' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup environment variables
        run: pnpm run env:set

      - name: Prepare staging environment
        run: pnpm run staging-remote:set

      - name: Run tests
        run: pnpm run staging-remote

      - name: Stop PostgreSQL
        if: always()
        run: docker compose down
